version: "3.9"
services:
  backend:
    build: .
    container_name: greenfox
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/resortdb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
      - JWT_SECRET=6323CC6741CDE96FB193FDE21719E
    depends_on:
      - db
      - redis

  db:
    image: postgres:16
    container_name: resort-db
    environment:
      POSTGRES_DB: resortdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: resort-redis
    ports:
      - "6379:6379"
