spring.application.name=greenfox-backend
# Server
server.port=8080

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/greenfox_db
spring.datasource.username=arsenal
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Logging
logging.level.org.springframework=INFO
