spring.application.name=greenfox-backend
# Server
server.port=8080

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/greenfox_db
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Logging
logging.level.org.springframework=INFO

jwt.secret=4A9D8D78A58C49DDA0BEB4EF0EAF8241F3BC7C63D739DCB445B96F38D5A0F2A3

